/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as ApiDashboardStudentRouteImport } from './routes/api/dashboard/student'
import { Route as ApiDashboardAdminRouteImport } from './routes/api/dashboard/admin'
import { Route as ApiAuthStudentLoginRouteImport } from './routes/api/auth/student-login'
import { Route as ApiAuthStaffLoginRouteImport } from './routes/api/auth/staff-login'
import { Route as AuthenticatedStudentResultsRouteImport } from './routes/_authenticated/student/results'
import { Route as AuthenticatedStudentPyqsRouteImport } from './routes/_authenticated/student/pyqs'
import { Route as AuthenticatedStudentNoticesRouteImport } from './routes/_authenticated/student/notices'
import { Route as AuthenticatedStudentNotesRouteImport } from './routes/_authenticated/student/notes'
import { Route as AuthenticatedStudentHomeworkRouteImport } from './routes/_authenticated/student/homework'
import { Route as AuthenticatedStudentFeesRouteImport } from './routes/_authenticated/student/fees'
import { Route as AuthenticatedStudentContactRouteImport } from './routes/_authenticated/student/contact'
import { Route as AuthenticatedStudentAttendanceRouteImport } from './routes/_authenticated/student/attendance'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin/teachers'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminResultsRouteImport } from './routes/_authenticated/admin/results'
import { Route as AuthenticatedAdminPyqsRouteImport } from './routes/_authenticated/admin/pyqs'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin/notices'
import { Route as AuthenticatedAdminNotesRouteImport } from './routes/_authenticated/admin/notes'
import { Route as AuthenticatedAdminHomeworkRouteImport } from './routes/_authenticated/admin/homework'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin/fees'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminStudentsIndexRouteImport } from './routes/_authenticated/admin/students.index'
import { Route as AuthenticatedAdminStudentsIdRouteImport } from './routes/_authenticated/admin/students.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStudentRoute = ApiDashboardStudentRouteImport.update({
  id: '/api/dashboard/student',
  path: '/api/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardAdminRoute = ApiDashboardAdminRouteImport.update({
  id: '/api/dashboard/admin',
  path: '/api/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStudentLoginRoute = ApiAuthStudentLoginRouteImport.update({
  id: '/api/auth/student-login',
  path: '/api/auth/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStaffLoginRoute = ApiAuthStaffLoginRouteImport.update({
  id: '/api/auth/staff-login',
  path: '/api/auth/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentResultsRoute =
  AuthenticatedStudentResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentPyqsRoute =
  AuthenticatedStudentPyqsRouteImport.update({
    id: '/pyqs',
    path: '/pyqs',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentNoticesRoute =
  AuthenticatedStudentNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentNotesRoute =
  AuthenticatedStudentNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentHomeworkRoute =
  AuthenticatedStudentHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentFeesRoute =
  AuthenticatedStudentFeesRouteImport.update({
    id: '/fees',
    path: '/fees',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentContactRoute =
  AuthenticatedStudentContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentAttendanceRoute =
  AuthenticatedStudentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResultsRoute =
  AuthenticatedAdminResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPyqsRoute = AuthenticatedAdminPyqsRouteImport.update({
  id: '/pyqs',
  path: '/pyqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotesRoute = AuthenticatedAdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHomeworkRoute =
  AuthenticatedAdminHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsIndexRoute =
  AuthenticatedAdminStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)
const AuthenticatedAdminStudentsIdRoute =
  AuthenticatedAdminStudentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/pyqs': typeof AuthenticatedAdminPyqsRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student/contact': typeof AuthenticatedStudentContactRoute
  '/student/fees': typeof AuthenticatedStudentFeesRoute
  '/student/homework': typeof AuthenticatedStudentHomeworkRoute
  '/student/notes': typeof AuthenticatedStudentNotesRoute
  '/student/notices': typeof AuthenticatedStudentNoticesRoute
  '/student/pyqs': typeof AuthenticatedStudentPyqsRoute
  '/student/results': typeof AuthenticatedStudentResultsRoute
  '/api/auth/staff-login': typeof ApiAuthStaffLoginRoute
  '/api/auth/student-login': typeof ApiAuthStudentLoginRoute
  '/api/dashboard/admin': typeof ApiDashboardAdminRoute
  '/api/dashboard/student': typeof ApiDashboardStudentRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/pyqs': typeof AuthenticatedAdminPyqsRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student/contact': typeof AuthenticatedStudentContactRoute
  '/student/fees': typeof AuthenticatedStudentFeesRoute
  '/student/homework': typeof AuthenticatedStudentHomeworkRoute
  '/student/notes': typeof AuthenticatedStudentNotesRoute
  '/student/notices': typeof AuthenticatedStudentNoticesRoute
  '/student/pyqs': typeof AuthenticatedStudentPyqsRoute
  '/student/results': typeof AuthenticatedStudentResultsRoute
  '/api/auth/staff-login': typeof ApiAuthStaffLoginRoute
  '/api/auth/student-login': typeof ApiAuthStudentLoginRoute
  '/api/dashboard/admin': typeof ApiDashboardAdminRoute
  '/api/dashboard/student': typeof ApiDashboardStudentRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/students': typeof AuthenticatedAdminStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/_authenticated/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/pyqs': typeof AuthenticatedAdminPyqsRoute
  '/_authenticated/admin/results': typeof AuthenticatedAdminResultsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/_authenticated/student/contact': typeof AuthenticatedStudentContactRoute
  '/_authenticated/student/fees': typeof AuthenticatedStudentFeesRoute
  '/_authenticated/student/homework': typeof AuthenticatedStudentHomeworkRoute
  '/_authenticated/student/notes': typeof AuthenticatedStudentNotesRoute
  '/_authenticated/student/notices': typeof AuthenticatedStudentNoticesRoute
  '/_authenticated/student/pyqs': typeof AuthenticatedStudentPyqsRoute
  '/_authenticated/student/results': typeof AuthenticatedStudentResultsRoute
  '/api/auth/staff-login': typeof ApiAuthStaffLoginRoute
  '/api/auth/student-login': typeof ApiAuthStudentLoginRoute
  '/api/dashboard/admin': typeof ApiDashboardAdminRoute
  '/api/dashboard/student': typeof ApiDashboardStudentRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/_authenticated/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/student'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/homework'
    | '/admin/notes'
    | '/admin/notices'
    | '/admin/pyqs'
    | '/admin/results'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/attendance'
    | '/student/contact'
    | '/student/fees'
    | '/student/homework'
    | '/student/notes'
    | '/student/notices'
    | '/student/pyqs'
    | '/student/results'
    | '/api/auth/staff-login'
    | '/api/auth/student-login'
    | '/api/dashboard/admin'
    | '/api/dashboard/student'
    | '/api/public/bootstrap'
    | '/admin/'
    | '/student/'
    | '/admin/students/$id'
    | '/admin/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/homework'
    | '/admin/notes'
    | '/admin/notices'
    | '/admin/pyqs'
    | '/admin/results'
    | '/admin/teachers'
    | '/student/attendance'
    | '/student/contact'
    | '/student/fees'
    | '/student/homework'
    | '/student/notes'
    | '/student/notices'
    | '/student/pyqs'
    | '/student/results'
    | '/api/auth/staff-login'
    | '/api/auth/student-login'
    | '/api/dashboard/admin'
    | '/api/dashboard/student'
    | '/api/public/bootstrap'
    | '/admin'
    | '/student'
    | '/admin/students/$id'
    | '/admin/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/student'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/homework'
    | '/_authenticated/admin/notes'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/pyqs'
    | '/_authenticated/admin/results'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/student/attendance'
    | '/_authenticated/student/contact'
    | '/_authenticated/student/fees'
    | '/_authenticated/student/homework'
    | '/_authenticated/student/notes'
    | '/_authenticated/student/notices'
    | '/_authenticated/student/pyqs'
    | '/_authenticated/student/results'
    | '/api/auth/staff-login'
    | '/api/auth/student-login'
    | '/api/dashboard/admin'
    | '/api/dashboard/student'
    | '/api/public/bootstrap'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/admin/students/$id'
    | '/_authenticated/admin/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthStaffLoginRoute: typeof ApiAuthStaffLoginRoute
  ApiAuthStudentLoginRoute: typeof ApiAuthStudentLoginRoute
  ApiDashboardAdminRoute: typeof ApiDashboardAdminRoute
  ApiDashboardStudentRoute: typeof ApiDashboardStudentRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/student': {
      id: '/api/dashboard/student'
      path: '/api/dashboard/student'
      fullPath: '/api/dashboard/student'
      preLoaderRoute: typeof ApiDashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/admin': {
      id: '/api/dashboard/admin'
      path: '/api/dashboard/admin'
      fullPath: '/api/dashboard/admin'
      preLoaderRoute: typeof ApiDashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/student-login': {
      id: '/api/auth/student-login'
      path: '/api/auth/student-login'
      fullPath: '/api/auth/student-login'
      preLoaderRoute: typeof ApiAuthStudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/staff-login': {
      id: '/api/auth/staff-login'
      path: '/api/auth/staff-login'
      fullPath: '/api/auth/staff-login'
      preLoaderRoute: typeof ApiAuthStaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/results': {
      id: '/_authenticated/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof AuthenticatedStudentResultsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/pyqs': {
      id: '/_authenticated/student/pyqs'
      path: '/pyqs'
      fullPath: '/student/pyqs'
      preLoaderRoute: typeof AuthenticatedStudentPyqsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/notices': {
      id: '/_authenticated/student/notices'
      path: '/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof AuthenticatedStudentNoticesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/notes': {
      id: '/_authenticated/student/notes'
      path: '/notes'
      fullPath: '/student/notes'
      preLoaderRoute: typeof AuthenticatedStudentNotesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/homework': {
      id: '/_authenticated/student/homework'
      path: '/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof AuthenticatedStudentHomeworkRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/fees': {
      id: '/_authenticated/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof AuthenticatedStudentFeesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/contact': {
      id: '/_authenticated/student/contact'
      path: '/contact'
      fullPath: '/student/contact'
      preLoaderRoute: typeof AuthenticatedStudentContactRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/attendance': {
      id: '/_authenticated/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof AuthenticatedStudentAttendanceRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/results': {
      id: '/_authenticated/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AuthenticatedAdminResultsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pyqs': {
      id: '/_authenticated/admin/pyqs'
      path: '/pyqs'
      fullPath: '/admin/pyqs'
      preLoaderRoute: typeof AuthenticatedAdminPyqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notes': {
      id: '/_authenticated/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AuthenticatedAdminNotesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homework': {
      id: '/_authenticated/admin/homework'
      path: '/homework'
      fullPath: '/admin/homework'
      preLoaderRoute: typeof AuthenticatedAdminHomeworkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students/': {
      id: '/_authenticated/admin/students/'
      path: '/'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
    '/_authenticated/admin/students/$id': {
      id: '/_authenticated/admin/students/$id'
      path: '/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIdRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
  }
}

interface AuthenticatedAdminStudentsRouteChildren {
  AuthenticatedAdminStudentsIdRoute: typeof AuthenticatedAdminStudentsIdRoute
  AuthenticatedAdminStudentsIndexRoute: typeof AuthenticatedAdminStudentsIndexRoute
}

const AuthenticatedAdminStudentsRouteChildren: AuthenticatedAdminStudentsRouteChildren =
  {
    AuthenticatedAdminStudentsIdRoute: AuthenticatedAdminStudentsIdRoute,
    AuthenticatedAdminStudentsIndexRoute: AuthenticatedAdminStudentsIndexRoute,
  }

const AuthenticatedAdminStudentsRouteWithChildren =
  AuthenticatedAdminStudentsRoute._addFileChildren(
    AuthenticatedAdminStudentsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminHomeworkRoute: typeof AuthenticatedAdminHomeworkRoute
  AuthenticatedAdminNotesRoute: typeof AuthenticatedAdminNotesRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminPyqsRoute: typeof AuthenticatedAdminPyqsRoute
  AuthenticatedAdminResultsRoute: typeof AuthenticatedAdminResultsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRouteWithChildren
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminHomeworkRoute: AuthenticatedAdminHomeworkRoute,
  AuthenticatedAdminNotesRoute: AuthenticatedAdminNotesRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminPyqsRoute: AuthenticatedAdminPyqsRoute,
  AuthenticatedAdminResultsRoute: AuthenticatedAdminResultsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRouteWithChildren,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentAttendanceRoute: typeof AuthenticatedStudentAttendanceRoute
  AuthenticatedStudentContactRoute: typeof AuthenticatedStudentContactRoute
  AuthenticatedStudentFeesRoute: typeof AuthenticatedStudentFeesRoute
  AuthenticatedStudentHomeworkRoute: typeof AuthenticatedStudentHomeworkRoute
  AuthenticatedStudentNotesRoute: typeof AuthenticatedStudentNotesRoute
  AuthenticatedStudentNoticesRoute: typeof AuthenticatedStudentNoticesRoute
  AuthenticatedStudentPyqsRoute: typeof AuthenticatedStudentPyqsRoute
  AuthenticatedStudentResultsRoute: typeof AuthenticatedStudentResultsRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentAttendanceRoute: AuthenticatedStudentAttendanceRoute,
  AuthenticatedStudentContactRoute: AuthenticatedStudentContactRoute,
  AuthenticatedStudentFeesRoute: AuthenticatedStudentFeesRoute,
  AuthenticatedStudentHomeworkRoute: AuthenticatedStudentHomeworkRoute,
  AuthenticatedStudentNotesRoute: AuthenticatedStudentNotesRoute,
  AuthenticatedStudentNoticesRoute: AuthenticatedStudentNoticesRoute,
  AuthenticatedStudentPyqsRoute: AuthenticatedStudentPyqsRoute,
  AuthenticatedStudentResultsRoute: AuthenticatedStudentResultsRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthStaffLoginRoute: ApiAuthStaffLoginRoute,
  ApiAuthStudentLoginRoute: ApiAuthStudentLoginRoute,
  ApiDashboardAdminRoute: ApiDashboardAdminRoute,
  ApiDashboardStudentRoute: ApiDashboardStudentRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
